<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PE-HO-274" failures="0" tests="1" name="com.FormularioNuevoFFP.test.CreacionNuevaDeclaracionTest" time="156.942" errors="1" timestamp="27 sep. 2022 15:11:41 GMT" skipped="0">
  <testcase classname="com.FormularioNuevoFFP.test.CreacionNuevaDeclaracionTest" name="CrearNuevaDeclaracionFFP" time="156.942">
    <error message="The document has been closed. You can&#039;t add any Elements." type="com.itextpdf.text.DocumentException">
      <![CDATA[com.itextpdf.text.DocumentException: The document has been closed. You can't add any Elements.
at com.itextpdf.text.Document.add(Document.java:267)
at utilities.GenerarReportePdf.closeTemplate(GenerarReportePdf.java:181)
at PagObject_demoautomatizacion.BasePage.click(BasePage.java:211)
at PagObject_FormularioNuevoFFP.NuevaDeclaracionPage.NuevaDeclaracionFFP(NuevaDeclaracionPage.java:31)
at com.FormularioNuevoFFP.test.CreacionNuevaDeclaracionTest.CrearNuevaDeclaracionFFP(CreacionNuevaDeclaracionTest.java:62)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CrearNuevaDeclaracionFFP -->
</testsuite> <!-- com.FormularioNuevoFFP.test.CreacionNuevaDeclaracionTest -->
